export { default as Header } from './Header';
export { default as LoggedHeader } from './LoggedHeader';
export { default as AuthenticatedHeader } from './AuthenticatedHeader';
export { default as Cover } from './Cover';
export { default as Card } from './Card';
export { default as Features } from './Features';
export { default as Note } from './Note';
export { default as Footer } from './Footer';
export { default as TermsConditions } from './Terms';
